name: latres
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0             # Akses API
  provider: ^6.1.1         # State Management
  
  # Hive (Database Lokal)
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Generator Kode (Wajib untuk Hive)
  hive_generator: ^2.0.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true